export interface BuzonTarjeta { nombre: string; palabras: string[] }

export const BUZONES: BuzonTarjeta[] = [
  { nombre: 'Herramientas', palabras: ['MARTILLO','LLAVE INGLESA','PALA','DESTORNILLADOR','PICO','SIERRA','TALADRO','TIJERAS','CÚTER','NIVEL','ALICATES','AGUJA','METRO','LAPICERO','TENAZAS','ESPÁTULA'] },
  { nombre: 'Hogar', palabras: ['COMIDA','REUNIÓN','PAPEL HIGIÉNICO','HORARIO','VACACIONES','CHARLA','TAREAS','JUEGOS DE MESA','FREGAR','HIJOS','COLEGIO','CUARTO','INTIMIDAD','PAGA','VISITA','CENA'] },
  { nombre: 'Instrumentos', palabras: ['FLAUTA','TAMBOR','ACORDEÓN','GUITARRA','BATERÍA','CASTAÑUELAS','PIANO','TUBA','SAXOFÓN','ARPA','BAJO','ARMÓNICA','TRIÁNGULO','CAMPANA','VIOLÍN','GAITA'] },
  { nombre: 'Oficina', palabras: ['JEFA','SECRETARIO','FIESTA','MATERIAL','TURNOS','PAPELEO','CLIENTE','UNIFORME','ORDENADOR','NUEVO','DESPIDO','CAFEÍNA','DESCANSO','ACCIONISTAS','PELOTA','ENCHUFE'] },
  { nombre: 'Países', palabras: ['REINO UNIDO','ESPAÑA','JAPÓN','BRASIL','FRANCIA','EEUU','ITALIA','AUSTRALIA','ALEMANIA','MÉXICO','INDIA','ISRAEL','CANADÁ','CHINA','RUSIA','EGIPTO'] },
  { nombre: 'Películas', palabras: ['MATRIX','ORIGEN','SEVEN','EL REY LEÓN','12 MONOS','CASABLANCA','EL CLUB DE LA LUCHA','LOS PÁJAROS','LOS VENGADORES','TITANIC','300','TORRENTE','AMELIE','DIRTY DANCING','CONAN EL BÁRBARO','SOLO EN CASA'] },
  { nombre: 'Política', palabras: ['ESCAÑO','LEY','CORRUPCIÓN','MITÍN','PRESIDENTE','VOTANTE','ELECCIONES','CANDIDATO','OBRAS','CAMPAÑA','COALICIÓN','OPOSICIÓN','MANIFESTACIÓN','CIUDADANOS','PROMESA','OFICIAL'] },
  { nombre: 'Prendas', palabras: ['GORRO','BAÑADOR','SUDADERA','TRAJE','FALDA','BUFANDA','CORBATA','CHANCLAS','CAPA','SOMBRERO','CINTURÓN','PIJAMA','LIGUERO','ZAPATOS','PAÑUELO','BRAGAS'] },
  { nombre: 'Salud', palabras: ['HOSPITAL','HIERRO','ACCIDENTE','CHEQUEO','EDAD','VITAMINAS','DIETA','CRECER','ALOPECIA','ENFERMEDAD','PRÓSTATA','HERENCIA','EMBARAZO','JUBILACIÓN','DEPORTE','OBESIDAD'] },
  { nombre: 'Superhéroes', palabras: ['SUPERMAN','BATMAN','SPIDERMAN','EL CASTIGADOR','CAPITÁN AMÉRICA','DR. EXTRAÑO','TORMENTA','LOBEZNO','EL COMEDIANTE','HULK','VIUDA NEGRA','JOHN CONSTANTINE','HELLBOY','SPAWN','JUEZ DREDD','HIT-GIRL'] },
  { nombre: 'Transporte', palabras: ['COCHE','SCOOTER','MOTO DE CARRERAS','HELICÓPTERO','NAVE ESPACIAL','CAZA DE COMBATE','BICICLETA','AVIÓN DE PASAJEROS','AUTOBÚS','TRANVÍA','GLOBO','COCHE','TREN','FURGONETA','MONOPATÍN','PATINES'] },
  { nombre: 'Vacaciones', palabras: ['BILLETES','VACUNA','ALOJAMIENTO','PLAYA','MONTAÑA','CRUCERO','VUELO','GUÍA','HOTEL','RESERVAR','TURISMO','CONDUCIR','RECUERDO','FOTOS','GASTRONOMÍA','MAPA'] }
]
